name: Deploy to Production

on:
  workflow_run:
    workflows: ['Thrift-app Testing']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Cache Node.js modules for faster builds
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store # or ~/.yarn for Yarn, ~/.pnpm-store for pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Or your preferred Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install vercel
        run: npm install -g vercel

      - name: Pull Vercel Project Metadata
        # Fetches vercel.json overrides, root directory, etc.
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Variables
        # Crucial for build-time env vars. Writes to .env.production, adjust as needed.
        run: vercel env pull .env.production --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Vercel Project
        # Uses the .env.production file for build-time environment variables
        run: vercel build --prod

      - name: Deploy to Vercel
        # Deploys the pre-built output from vercel build
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
