-- Fake data for product_reviews
insert into public.product_reviews (order_item_id, rating, customer_id, customer_remark) values
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Laptop Pro X') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22' and store_id = (select store_id from stores where vendor_id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11' LIMIT 1) LIMIT 1) LIMIT 1)), 4.50, 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Great laptop, very fast!'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Classic Leather Jacket') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44' and store_id = (select store_id from stores where vendor_id = 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33' LIMIT 1) LIMIT 1) LIMIT 1)), 5.00, 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'High quality leather, perfect fit.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Organic Skincare Kit') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a66' and store_id = (select store_id from stores where vendor_id = 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55' LIMIT 1) LIMIT 1) LIMIT 1)), 4.00, 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a66', 'Good product, but a bit pricey.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Curved Gaming Monitor') LIMIT 1) and order_id = (select order_id from orders where customer_id = '14eebc99-9c0b-4ef8-bb6d-6bb9bd380a99' and store_id = (select store_id from stores where vendor_id = 'a2eebc99-9c0b-4ef8-bb6d-6bb9bd380a77' LIMIT 1) LIMIT 1) LIMIT 1)), 4.80, '14eebc99-9c0b-4ef8-bb6d-6bb9bd380a99', 'Amazing display for gaming!'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Evening Gown Elegant') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22' and store_id = (select store_id from stores where vendor_id = 'e3eebc99-9c0b-4ef8-bb6d-6bb9bd380a88' LIMIT 1) LIMIT 1) LIMIT 1)), 5.00, 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Absolutely stunning dress, exceeded expectations.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Coffee Maker Drip') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44' and store_id = (select store_id from stores where vendor_id = '45eebc99-9c0b-4ef8-bb6d-6bb9bd380b00' limit 1) LIMIT 1) LIMIT 1)), 3.50, 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'Works well, but a bit slow.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Travel Backpack 40L') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a66' and store_id = (select store_id from stores where vendor_id = '14eebc99-9c0b-4ef8-bb6d-6bb9bd380a99' LIMIT 1) LIMIT 1) LIMIT 1)), 4.20, 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a66', 'Spacious and comfortable for travel.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Hand-painted Ceramic Mug') LIMIT 1) and order_id = (select order_id from orders where customer_id = '14eebc99-9c0b-4ef8-bb6d-6bb9bd380a99' and store_id = (select store_id from stores where vendor_id = 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44' LIMIT 1) LIMIT 1) LIMIT 1)), 4.90, '14eebc99-9c0b-4ef8-bb6d-6bb9bd380a99', 'Beautiful craftsmanship, love it!'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'High-Performance Gaming Laptop') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22' and store_id = (select store_id from stores where vendor_id = 'a2eebc99-9c0b-4ef8-bb6d-6bb9bd380a77' LIMIT 1) LIMIT 1) LIMIT 1)), 4.70, 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'Super powerful, runs all games smoothly.'),
(((select order_item_id from order_items where variant_id = (select variant_id from product_variants where product_id = (select product_id from products where title = 'Women''s Denim Jeans') LIMIT 1) and order_id = (select order_id from orders where customer_id = 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44' and store_id = (select store_id from stores where vendor_id = '45eebc99-9c0b-4ef8-bb6d-6bb9bd380b00' LIMIT 1) LIMIT 1) LIMIT 1)), 4.00, 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'Comfortable and stylish, good value.');

